apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379        # Redis port inside cluster
      targetPort: 6379
      nodePort: 30379   # Port on the node
