apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gameserver
  template:
    metadata:
      labels:
        app: gameserver
        prometheus-scrape: "true"
    spec:
      containers:
        - name: gameserver
          image: dota2classic/gameserver:k8s-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5003
              name: http-public

          resources:
            requests:
              cpu: 250m       # Pod asks for 0.25 CPU
              memory: 256Mi
            limits:
              cpu: 500m       # Pod can use up to 0.5 CPU
              memory: 512Mi

          envFrom:
            - secretRef:
                name: shared-secrets
          env:
            - name: APP_NAME
              value: "gameserver"
            - name: NODE_ENV
              value: "production"
