# ./k8s/gameserver/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gameserver
spec:
  type: NodePort
  selector:
    app: gameserver
  ports:
    - port: 5003
      targetPort: 5003
      nodePort: 30003
