apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
data:
  fluent-bit.conf: |
    [INPUT]
      Name              forward
    
    [OUTPUT]
      name   loki
      match  *
      host   141.105.71.200
      port   3100
      labels agent=fluent-bit, application=$application, logger=$context
