apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentbit
  template:
    metadata:
      labels:
        app: fluentbit
    spec:
      containers:
        - name: fluentbit
          image: fluent/fluent-bit:3.1
          args: ["-c", "/fluent-bit/etc/fluent-bit.conf"]
          ports:
            - containerPort: 24224
          volumeMounts:
            - name: fluentbit-config
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
          envFrom:
            - secretRef:
                name: shared-secrets
      volumes:
        - name: fluentbit-config
          configMap:
            name: fluentbit-config
