apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum
spec:
  replicas: 2
  selector:
    matchLabels:
      app: forum
  template:
    metadata:
      labels:
        app: forum
    spec:
      nodeSelector:
        ru.dotaclassic/nodeType: "infra"
      containers:
        - name: forum
          image: dota2classic/forum:k8s-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6009

          resources:
            requests:
              cpu: 15m
              memory: 110Mi
            limits:
              cpu: 200m
              memory: 250Mi
          envFrom:
            - secretRef:
                name: shared-secrets
          env:
            - name: APP_NAME
              value: "forum"
            - name: NODE_ENV
              value: "production"
