apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum
spec:
  replicas: 2
  selector:
    matchLabels:
      app: forum
  template:
    metadata:
      labels:
        app: forum
    spec:
      containers:
        - name: forum
          image: dota2classic/forum:k8s-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6009

          resources:
            requests:
              cpu: 250m       # Pod asks for 0.25 CPU
              memory: 256Mi
            limits:
              cpu: 500m       # Pod can use up to 0.5 CPU
              memory: 512Mi
          envFrom:
            - secretRef:
                name: shared-secrets
          env:
            - name: APP_NAME
              value: "forum"
            - name: NODE_ENV
              value: "production"
