apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      nodeSelector:
        ru.dotaclassic/nodeType: "infra"
      containers:
        - name: wiki
          image: dota2classic/wiki:k8s-latest
          imagePullPolicy: Always

          resources:
            requests:
              cpu: 10m
              memory: 110Mi
            limits:
              cpu: 120m
              memory: 160Mi
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: IS_DEV_VERSION
              value: "true"
