apiVersion: apps/v1
kind: Deployment
metadata:
  name: tournament
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tournament
  template:
    metadata:
      labels:
        app: tournament
        prometheus-scrape: "true"
    spec:
      nodeSelector:
        ru.dotaclassic/nodeType: "infra"
      containers:
        - name: tournament
          image: dota2classic/tournament:k8s-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6600
              name: http-public

          resources:
            requests:
              cpu: 10m
              memory: 96Mi
            limits:
              cpu: 100m
              memory: 150Mi

          envFrom:
            - secretRef:
                name: shared-secrets
          env:
            - name: APP_NAME
              value: "tournament"
            - name: NODE_ENV
              value: "production"
