apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: default
spec:
  clusterIP: None  # Headless service
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
  selector:
    app: rabbitmq
