apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432        # Postgres port inside cluster
      targetPort: 5432
      nodePort: 30555   # Port on the node
