apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-backup
  template:
    metadata:
      labels:
        app: postgres-backup
    spec:
      containers:
        - name: postgres-backup
          image: eeshugerman/postgres-backup-s3:16

          envFrom:
            - secretRef:
                name: shared-secrets
          env:
            - name: S3_REGION
              value: "eu-west-1"
            - name: SCHEDULE
              value: "@hourly"
            - name: BACKUP_KEEP_DAYS
              value: "7"
            - name: S3_BUCKET
              value: "backup"
            - name: S3_PREFIX
              value: "backup"
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: S3_ENDPOINT
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: S3_ACCESS_KEY_ID
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: S3_ACCESS_KEY_SECRET
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DATABASE
              value: "postgres"

