apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: default
data:
  postgresql.conf: |
    # Custom PostgreSQL configuration
    max_connections = 300
    shared_buffers = 512MB
    listen_addresses = '*'
