apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: dota2classic/user:k8s-latest
          imagePullPolicy: Always

          resources:
            requests:
              cpu: 200m       # Pod asks for 0.25 CPU
              memory: 128Mi
            limits:
              cpu: 300m       # Pod can use up to 0.5 CPU
              memory: 256Mi

          envFrom:
            - secretRef:
                name: shared-secrets
          env:
            - name: APP_NAME
              value: "user"
            - name: NODE_ENV
              value: "production"
