apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      nodeSelector:
        ru.dotaclassic/nodeType: "infra"
      containers:
        - name: user
          image: dota2classic/user:k8s-latest
          imagePullPolicy: Always

          resources:
            requests:
              cpu: 10m
              memory: 96Mi
            limits:
              cpu: 100m
              memory: 128Mi

          envFrom:
            - secretRef:
                name: shared-secrets
          env:
            - name: APP_NAME
              value: "user"
            - name: NODE_ENV
              value: "production"
