apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchmaker
  template:
    metadata:
      labels:
        app: matchmaker
    spec:
      containers:
        - name: matchmaker
          image: dota2classic/matchmaker:k8s-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7777

          resources:
            requests:
              cpu: 250m       # Pod asks for 0.25 CPU
              memory: 256Mi
            limits:
              cpu: 500m       # Pod can use up to 0.5 CPU
              memory: 512Mi

          envFrom:
            - secretRef:
                name: shared-secrets
          env:
            - name: APP_NAME
              value: "gateway"
            - name: NODE_ENV
              value: "production"
            - name: GAMESERVER_API
              value: "http://gameserver:5003"
