apiVersion: apps/v1
kind: Deployment
metadata:
  name: tg-announcer-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tg-announcer-bot
  template:
    metadata:
      labels:
        app: tg-announcer-bot
    spec:
      nodeSelector:
        ru.dotaclassic/nodeType: "infra"
      containers:
        - name: tg-announcer-bot
          image: dota2classic/tg-bot:latest
          imagePullPolicy: Always

          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 80Mi

          envFrom:
            - secretRef:
                name: shared-secrets
          env:
            - name: APP_NAME
              value: "tg-announcer-bot"
            - name: NODE_ENV
              value: "production"
