apiVersion: batch/v1
kind: CronJob
metadata:
  name: prepull-gameserver
  namespace: gameservers
  labels:
    app-type: gameserver
spec:
  schedule: "*/1 * * * *"  # every 1 minute
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          nodeSelector:
            node-type: "gameserver"
          tolerations:
            - effect: NoSchedule
              operator: Exists
          restartPolicy: OnFailure
          containers:
            - name: prepull-sidecar
              image: dota2classic/srcds-sidecar:k8s-latest
              imagePullPolicy: Always
              command: ["sh", "-c", "echo Pulled sidecar image"]
            - name: prepull-gameserver
              image: dota2classic/srcds:d684_dev-k8s-latest
              imagePullPolicy: Always
              command: ["sh", "-c", "echo Pulled gameserver image"]
