apiVersion: batch/v1
kind: CronJob
metadata:
  name: prepull-gameserver
  namespace: gameservers
  labels:
    app-type: gameserver
spec:
  schedule: "*/5 * * * *"  # every 5 minutes
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          nodeSelector:
            ru.dotaclassic/nodeType: "gameserver"
          tolerations:
            - effect: NoSchedule
              operator: Exists
          restartPolicy: OnFailure
          containers:
            - name: prepull-sidecar
              image: dota2classic/srcds-sidecar:k8s-latest
              imagePullPolicy: Always
              command: ["sh", "-c", "echo Pulled sidecar image"]
            - name: prepull-gameserver-base
              image: dota2classic/srcds:d684-latest
              imagePullPolicy: Always
              command: ["sh", "-c", "echo Pulled base gameserver image"]
            - name: prepull-gameserver-turbo
              image: dota2classic/srcds:d684-turbo-latest
              imagePullPolicy: Always
              command: [ "sh", "-c", "echo Pulled turbo gameserver image" ]
