apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-prepull
  namespace: gameservers
  labels:
    app: image-prepull
spec:
  selector:
    matchLabels:
      app: image-prepull
  template:
    metadata:
      labels:
        app: image-prepull
    spec:
      nodeSelector:
        ru.dotaclassic/nodeType: "gameserver"
      hostNetwork: true
      hostPID: true
      containers:
        - name: prepull
          securityContext:
            privileged: true
          image: rancher/k3s:v1.33.5-k3s1  # includes ctr
          command:
            - /bin/sh
            - -c
            - |
              while true; do
                for img in dota2classic/srcds-sidecar:k8s-latest \
                           dota2classic/srcds:d684-latest \
                           dota2classic/srcds:d684-turbo-latest; do
                  echo "Pulling $img on host..."
                  ctr -n k8s.io images pull $img || echo "Failed to pull $img"
                done
                sleep 300
              done
          volumeMounts:
            - name: containerd-sock
              mountPath: /run/containerd/containerd.sock
      volumes:
        - name: containerd-sock
          hostPath:
            path: /run/containerd/containerd.sock
      tolerations:
        - effect: NoSchedule
          key: gameserver
          operator: Exists
